n2p2 - A neural network potential package: nnp::GradientDescent Class Reference
nnp::GradientDescent Class Reference
#include <GradientDescent.h>
Public Types
enum DescentType { DT_FIXED }
Public Member Functions
GradientDescent (DescentType const type, std::size_t const sizeState)
GradientDescent class constructor.
~GradientDescent ()
Destructor.
void setState (double *state)
Set state vector.
void setError (double const *const error)
Set error.
void setDerivativeMatrix (double const *const derivatives)
Set derivative matrix.
void update ()
Perform connection update.
void setParametersFixed (double const eta)
Set parameters for gradient descent algorithm.
std::string status (std::size_t epoch) const
Status report.
std::vector< std::string > statusHeader () const
Header for status report file.
std::vector< std::string > info () const
Information about gradient descent settings.
Public Member Functions inherited from nnp::Updater
virtual ~Updater ()
Constructor.
Private Attributes
DescentType type
std::size_t sizeState
Number of neural network connections (weights + biases).
double eta
Learning rate .
double * state
State vector pointer.
double const * error
Error pointer (single double value).
double const * derivatives
Derivatives vector pointer.
Additional Inherited Members
Protected Member Functions inherited from nnp::Updater
Updater ()
Constructor.
Detailed Description
Definition at line 28 of file GradientDescent.h.
Member Enumeration Documentation
enum nnp::GradientDescent::DescentType
Enumerator
DT_FIXED
Definition at line 31 of file GradientDescent.h.
     {
         // Fixed step size.
         DT_FIXED
     };
Constructor & Destructor Documentation
GradientDescent::GradientDescent (DescentType const type, std::size_t const sizeState)
GradientDescent class constructor.
Parameters
[in] type Descent type used for step size.
[in] sizeState Number of neural network connections (weights and biases).
Definition at line 24 of file GradientDescent.cpp.
References DT_FIXED, sizeState, and type.
                                                               :
     Updater(),
     sizeState  (0          ),
     eta        (0.0        ),
     state      (NULL       ),
     error      (NULL       ),
     derivatives(NULL       )
 {
     if (!(type == DT_FIXED))
     {
         throw runtime_error("ERROR: Unknown GradientDescent type.\n");
     }
     if (sizeState < 1)
     {
         throw runtime_error("ERROR: Wrong GradientDescent dimensions.\n");
     }
     this->type = type;
     this->sizeState = sizeState;
 }
nnp::GradientDescent::~GradientDescent () inline
Destructor.
Definition at line 46 of file GradientDescent.h.
References derivatives, error, eta, info(), setDerivativeMatrix(), setError(), setParametersFixed(), setState(), state, status(), statusHeader(), and update().
 {};
Member Function Documentation
void GradientDescent::setState (double * state) virtual
Set state vector.
Parameters
[in,out] state State vector (changed in-place upon calling update()).
Implements nnp::Updater.
Definition at line 47 of file GradientDescent.cpp.
References state.
Referenced by ~GradientDescent().
 {
     this->state = state;
     return;
 }
void GradientDescent::setError (double const *const error) virtual
Set error.
Parameters
[in] error Error value (left unchanged).
Implements nnp::Updater.
Definition at line 54 of file GradientDescent.cpp.
References error.
Referenced by ~GradientDescent().
 {
     this->error = error;
     return;
 }
void GradientDescent::setDerivativeMatrix (double const *const derivatives) virtual
Set derivative matrix.
Parameters
[in] derivatives Derivative matrix (left unchanged).
Implements nnp::Updater.
Definition at line 61 of file GradientDescent.cpp.
References derivatives.
Referenced by ~GradientDescent().
 {
     this->derivatives = derivatives;
     return;
 }
void GradientDescent::update () virtual
Perform connection update.
Update the connections via steepest descent method.
Implements nnp::Updater.
Definition at line 68 of file GradientDescent.cpp.
References derivatives, eta, sizeState, and state.
Referenced by ~GradientDescent().
 {
     for (std::size_t i = 0; i < sizeState; ++i)
     {
         state[i] -= eta * (*error) * -derivatives[i];
     }
     return;
 }
void GradientDescent::setParametersFixed (double const eta)
Set parameters for gradient descent algorithm.
Parameters
[in] eta Step size = ratio of gradient subtracted from current weights.
Definition at line 78 of file GradientDescent.cpp.
References eta.
Referenced by nnp::Training::setupTraining(), and ~GradientDescent().
 {
     this->eta = eta;
     return;
 }
string GradientDescent::status (std::size_t epoch) const virtual
Status report.
Parameters
[in] epoch Current epoch.
Returns
Line with current status information.
Implements nnp::Updater.
Definition at line 85 of file GradientDescent.cpp.
References eta, and nnp::strpr().
Referenced by ~GradientDescent().
 {
     return strpr("%10zu %16.8E\n", epoch, eta);
 }
vector< string > GradientDescent::statusHeader () const virtual
Header for status report file.
Returns
Vector with header lines.
Implements nnp::Updater.
Definition at line 90 of file GradientDescent.cpp.
References nnp::createFileHeader().
Referenced by ~GradientDescent().
 {
     vector<string> header;
     vector<string> title;
     vector<string> colName;
     vector<string> colInfo;
     vector<size_t> colSize;
     title.push_back("Gradient descent status report.");
     colSize.push_back(10);
     colName.push_back("epoch");
     colInfo.push_back("Training epoch.");
     colSize.push_back(16);
     colName.push_back("eta");
     colInfo.push_back("Step size.");
     header = createFileHeader(title, colSize, colName, colInfo);
     return header;
 }
vector< string > GradientDescent::info () const virtual
Information about gradient descent settings.
Returns
Vector with info lines.
Implements nnp::Updater.
Definition at line 110 of file GradientDescent.cpp.
References DT_FIXED, eta, sizeState, nnp::strpr(), and type.
Referenced by ~GradientDescent().
 {
     vector<string> v;
     if (type == DT_FIXED)
     {
         v.push_back(strpr("GradientDescentType::DT_FIXED (%d)\n", type));
         v.push_back(strpr("sizeState       = %zu\n", sizeState));
         v.push_back(strpr("eta             = %12.4E\n", eta));
     }
     return v;
 }
Member Data Documentation
DescentType nnp::GradientDescent::type private
Definition at line 94 of file GradientDescent.h.
Referenced by GradientDescent(), and info().
std::size_t nnp::GradientDescent::sizeState private
Number of neural network connections (weights + biases).
Definition at line 96 of file GradientDescent.h.
Referenced by GradientDescent(), info(), and update().
double nnp::GradientDescent::eta private
Learning rate .
Definition at line 98 of file GradientDescent.h.
Referenced by info(), setParametersFixed(), status(), update(), and ~GradientDescent().
double* nnp::GradientDescent::state private
State vector pointer.
Definition at line 100 of file GradientDescent.h.
Referenced by setState(), update(), and ~GradientDescent().
double const* nnp::GradientDescent::error private
Error pointer (single double value).
Definition at line 102 of file GradientDescent.h.
Referenced by setError(), and ~GradientDescent().
double const* nnp::GradientDescent::derivatives private
Derivatives vector pointer.
Definition at line 104 of file GradientDescent.h.
Referenced by setDerivativeMatrix(), update(), and ~GradientDescent().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnptrain/GradientDescent.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnptrain/GradientDescent.cpp