n2p2 - A neural network potential package: nnp::SetupAnalysis Class Reference
nnp::SetupAnalysis Class Reference
#include <SetupAnalysis.h>
Public Member Functions
void writeSymmetryFunctionShape (std::size_t numPoints, std::string const fileNameFormat="sf.%03zu.%04zu.out")
Write radial and angular part of symmetry functions to file.
Public Member Functions inherited from nnp::Mode
Mode ()
void initialize ()
Write welcome message with version information.
void loadSettingsFile (std::string const &fileName="input.nn")
Open settings file and load all keywords into memory.
void setupGeneric ()
Combine multiple setup routines and provide a basic NNP setup.
void setupNormalization ()
Set up normalization.
void setupElementMap ()
Set up the element map.
void setupElements ()
Set up all Element instances.
void setupCutoff ()
Set up cutoff function for all symmetry functions.
void setupSymmetryFunctions ()
Set up all symmetry functions.
void setupSymmetryFunctionScalingNone ()
Set up "empy" symmetry function scaling.
void setupSymmetryFunctionScaling (std::string const &fileName="scaling.data")
Set up symmetry function scaling from file.
void setupSymmetryFunctionGroups ()
Set up symmetry function groups.
void setupSymmetryFunctionStatistics (bool collectStatistics, bool collectExtrapolationWarnings, bool writeExtrapolationWarnings, bool stopOnExtrapolationWarnings)
Set up symmetry function statistics collection.
void setupNeuralNetwork ()
Set up neural networks for all elements.
void setupNeuralNetworkWeights (std::string const &fileNameFormat="weights.%03zu.data")
Set up neural network weights from files.
void calculateSymmetryFunctions (Structure &structure, bool const derivatives)
Calculate all symmetry functions for all atoms in given structure.
void calculateSymmetryFunctionGroups (Structure &structure, bool const derivatives)
Calculate all symmetry function groups for all atoms in given structure.
void calculateAtomicNeuralNetworks (Structure &structure, bool const derivatives) const
Calculate atomic neural networks for all atoms in given structure.
void calculateEnergy (Structure &structure) const
Calculate potential energy for a given structure.
void calculateForces (Structure &structure) const
Calculate forces for all atoms in given structure.
void addEnergyOffset (Structure &structure, bool ref=true)
void removeEnergyOffset (Structure &structure, bool ref=true)
double getEnergyOffset (Structure const &structure) const
double getEnergyWithOffset (Structure const &structure, bool ref=true) const
double normalizedEnergy (double energy) const
Apply normalization to given energy.
double normalizedEnergy (Structure const &structure, bool ref=true) const
Apply normalization to given energy of structure.
double normalizedForce (double force) const
Apply normalization to given force.
double physicalEnergy (double energy) const
Undo normalization for a given energy.
double physicalEnergy (Structure const &structure, bool ref=true) const
Undo normalization for a given energy of structure.
double physicalForce (double force) const
Undo normalization for a given force.
void convertToNormalizedUnits (Structure &structure) const
Convert one structure to normalized units.
void convertToPhysicalUnits (Structure &structure) const
Convert one structure to physical units.
std::size_t getNumExtrapolationWarnings () const
Count total number of extrapolation warnings encountered for all elements and symmetry functions.
void resetExtrapolationWarnings ()
Erase all extrapolation warnings and reset counters.
double getMeanEnergy () const
Getter for Mode::meanEnergy.
double getConvEnergy () const
Getter for Mode::convEnergy.
double getConvLength () const
Getter for Mode::convLength.
double getMaxCutoffRadius () const
Getter for Mode::maxCutoffRadius.
std::size_t getNumElements () const
Getter for Mode::numElements.
std::vector< std::size_t > getNumSymmetryFunctions () const
Get number of symmetry functions per element.
bool useNormalization () const
Check if normalization is enabled.
bool settingsKeywordExists (std::string const &keyword) const
Check if keyword was found in settings file.
std::string settingsGetValue (std::string const &keyword) const
Get value for given keyword in Settings instance.
std::vector< std::size_t > pruneSymmetryFunctionsRange (double threshold)
Prune symmetry functions according to their range and write settings file.
std::vector< std::size_t > pruneSymmetryFunctionsSensitivity (double threshold, std::vector< std::vector< double > > sensitivity)
Prune symmetry functions with sensitivity analysis data.
void writePrunedSettingsFile (std::vector< std::size_t > prune, std::string fileName="output.nn") const
Copy settings file but comment out lines provided.
void writeSettingsFile (std::ofstream *const &file) const
Write complete settings file.
Additional Inherited Members
Public Attributes inherited from nnp::Mode
ElementMap elementMap
Global element map, populated by setupElementMap().
Log log
Global log file.
Protected Attributes inherited from nnp::Mode
bool normalize
bool checkExtrapolationWarnings
std::size_t numElements
std::vector< std::size_t > minNeighbors
std::vector< double > minCutoffRadius
double maxCutoffRadius
double cutoffAlpha
double meanEnergy
double convEnergy
double convLength
Settings settings
SymmetryFunction::ScalingType scalingType
CutoffFunction::CutoffType cutoffType
std::vector< Element > elements
Detailed Description
Definition at line 26 of file SetupAnalysis.h.
Member Function Documentation
void SetupAnalysis::writeSymmetryFunctionShape (std::size_t numPoints, std::string const fileNameFormat = "sf.%03zu.%04zu.out")
Write radial and angular part of symmetry functions to file.
Parameters
[in] numPoints Number of symmetry function points to plot.
[in] fileNameFormat File name with place holder for element and symmetry function number.
Definition at line 24 of file SetupAnalysis.cpp.
References nnp::appendLinesToFile(), nnp::SymmetryFunction::calculateAngularPart(), nnp::SymmetryFunction::calculateRadialPart(), nnp::createFileHeader(), nnp::Element::getAtomicNumber(), nnp::SymmetryFunction::getIndex(), nnp::Element::getSymmetryFunction(), nnp::Element::infoSymmetryFunction(), log, nnp::Element::numSymmetryFunctions(), and nnp::strpr().
Referenced by main().
 {
     log << "\n";
     log << "*** ANALYSIS: SYMMETRY FUNCTION SHAPE ***"
            "**************************************\n";
     log << "\n";
     log << strpr("Symmetry function file name format: %s\n",
                  fileNameFormat.c_str());
     log << strpr("Number of points                  : %zu\n", numPoints);
     double dr = getMaxCutoffRadius() / numPoints;
     log << strpr("Distance step                     : %f\n", dr);
     double da = M_PI / numPoints;
     log << strpr("Angle step (radians)              : %f\n", da);
     for (size_t i = 0; i < numElements; ++i)
     {
         Element const& e = elements.at(i);
         for (size_t j = 0; j < e.numSymmetryFunctions(); ++j)
         {
             SymmetryFunction const& s = e.getSymmetryFunction(j);
             ofstream file;
             file.open(strpr(fileNameFormat.c_str(),
                             e.getAtomicNumber(),
                             j + 1).c_str());
             vector<string> info = e.infoSymmetryFunction(s.getIndex());
             for (vector<string>::const_iterator it = info.begin();
                  it != info.end(); ++it)
             {
                 file << strpr("#SFINFO %s\n", it->c_str());
             }
             // File header.
             vector<string> title;
             vector<string> colName;
             vector<string> colInfo;
             vector<size_t> colSize;
             title.push_back("Symmetry function shape.");
             colSize.push_back(16);
             colName.push_back("distance");
             colInfo.push_back("Distance from center.");
             colSize.push_back(16);
             colName.push_back("sf_radial");
             colInfo.push_back("Radial part of symmetry function at given "
                               "distance.");
             colSize.push_back(16);
             colName.push_back("angle");
             colInfo.push_back("Angle in degrees.");
             colSize.push_back(16);
             colName.push_back("sf_angular");
             colInfo.push_back("Angular part of symmetry function at given "
                               "angle.");
             appendLinesToFile(file,
                               createFileHeader(title,
                                                colSize,
                                                colName,
                                                colInfo));
             for (size_t k = 0; k < numPoints + 1; ++k)
             {
                 file << strpr("%16.8E %16.8E %16.8E %16.8E\n",
                               k * dr,
                               s.calculateRadialPart(k * dr),
                               k * da,
                               s.calculateAngularPart(k * da));
             }
             file.close();
         }
     }
     log << "*****************************************"
            "**************************************\n";
     return;
 }
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SetupAnalysis.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/SetupAnalysis.cpp