n2p2 - A neural network potential package: nnp::Updater Class Reference
nnp::Updater Class Reference abstract
Base class for different weight update methods.
#include <Updater.h>
Public Member Functions
virtual ~Updater ()
Constructor.
virtual void setState (double *state)=0
Set pointer to current state.
virtual void setError (double const *const error)=0
Set pointer to current error.
virtual void setDerivativeMatrix (double const *const derivatives)=0
Set pointer to derivative matrix.
virtual void update ()=0
Perform update of state vector.
virtual std::string status (std::size_t epoch) const =0
Status report.
virtual std::vector< std::string > statusHeader () const =0
Header for status report file.
virtual std::vector< std::string > info () const =0
Information about this updater.
Protected Member Functions
Updater ()
Constructor.
Detailed Description
Base class for different weight update methods.
Definition at line 27 of file Updater.h.
Constructor & Destructor Documentation
virtual nnp::Updater::~Updater () inline virtual
Constructor.
Definition at line 32 of file Updater.h.
References info(), setDerivativeMatrix(), setError(), setState(), status(), statusHeader(), update(), and Updater().
 {};
Updater::Updater () protected
Constructor.
Definition at line 21 of file Updater.cpp.
Referenced by ~Updater().
 {
 }
Member Function Documentation
virtual void nnp::Updater::setState (double * state) pure virtual
Set pointer to current state.
Parameters
[in,out] state Pointer to state (weights vector).
Implemented in nnp::KalmanFilter, and nnp::GradientDescent.
Referenced by ~Updater().
virtual void nnp::Updater::setError (double const *const error) pure virtual
Set pointer to current error.
Parameters
[in] error Pointer to error (difference between reference and neural network potential output).
Implemented in nnp::KalmanFilter, and nnp::GradientDescent.
Referenced by ~Updater().
virtual void nnp::Updater::setDerivativeMatrix (double const *const derivatives) pure virtual
Set pointer to derivative matrix.
Parameters
[in] derivatives Derivatives of error with respect to weights.
Implemented in nnp::KalmanFilter, and nnp::GradientDescent.
Referenced by ~Updater().
virtual void nnp::Updater::update () pure virtual
Perform update of state vector.
Implemented in nnp::KalmanFilter, and nnp::GradientDescent.
Referenced by ~Updater().
virtual std::string nnp::Updater::status (std::size_t epoch) const pure virtual
Status report.
Parameters
[in] epoch Current epoch.
Returns
Line with current status information.
Implemented in nnp::KalmanFilter, and nnp::GradientDescent.
Referenced by ~Updater().
virtual std::vector<std::string> nnp::Updater::statusHeader () const pure virtual
Header for status report file.
Returns
Vector with header lines.
Implemented in nnp::KalmanFilter, and nnp::GradientDescent.
Referenced by ~Updater().
virtual std::vector<std::string> nnp::Updater::info () const pure virtual
Information about this updater.
Returns
Vector of information lines.
Implemented in nnp::KalmanFilter, and nnp::GradientDescent.
Referenced by ~Updater().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnptrain/Updater.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnptrain/Updater.cpp