n2p2 - A neural network potential package: nnp::Prediction Class Reference
nnp::Prediction Class Reference
#include <Prediction.h>
Public Member Functions
Prediction ()
void readStructureFromFile (std::string const &fileName="input.data")
void setup ()
void predict ()
Public Member Functions inherited from nnp::Mode
Mode ()
void initialize ()
Write welcome message with version information.
void loadSettingsFile (std::string const &fileName="input.nn")
Open settings file and load all keywords into memory.
void setupGeneric ()
Combine multiple setup routines and provide a basic NNP setup.
void setupNormalization ()
Set up normalization.
void setupElementMap ()
Set up the element map.
void setupElements ()
Set up all Element instances.
void setupCutoff ()
Set up cutoff function for all symmetry functions.
void setupSymmetryFunctions ()
Set up all symmetry functions.
void setupSymmetryFunctionScalingNone ()
Set up "empy" symmetry function scaling.
void setupSymmetryFunctionScaling (std::string const &fileName="scaling.data")
Set up symmetry function scaling from file.
void setupSymmetryFunctionGroups ()
Set up symmetry function groups.
void setupSymmetryFunctionStatistics (bool collectStatistics, bool collectExtrapolationWarnings, bool writeExtrapolationWarnings, bool stopOnExtrapolationWarnings)
Set up symmetry function statistics collection.
void setupNeuralNetwork ()
Set up neural networks for all elements.
void setupNeuralNetworkWeights (std::string const &fileNameFormat="weights.%03zu.data")
Set up neural network weights from files.
void calculateSymmetryFunctions (Structure &structure, bool const derivatives)
Calculate all symmetry functions for all atoms in given structure.
void calculateSymmetryFunctionGroups (Structure &structure, bool const derivatives)
Calculate all symmetry function groups for all atoms in given structure.
void calculateAtomicNeuralNetworks (Structure &structure, bool const derivatives) const
Calculate atomic neural networks for all atoms in given structure.
void calculateEnergy (Structure &structure) const
Calculate potential energy for a given structure.
void calculateForces (Structure &structure) const
Calculate forces for all atoms in given structure.
void addEnergyOffset (Structure &structure, bool ref=true)
void removeEnergyOffset (Structure &structure, bool ref=true)
double getEnergyOffset (Structure const &structure) const
double getEnergyWithOffset (Structure const &structure, bool ref=true) const
double normalizedEnergy (double energy) const
Apply normalization to given energy.
double normalizedEnergy (Structure const &structure, bool ref=true) const
Apply normalization to given energy of structure.
double normalizedForce (double force) const
Apply normalization to given force.
double physicalEnergy (double energy) const
Undo normalization for a given energy.
double physicalEnergy (Structure const &structure, bool ref=true) const
Undo normalization for a given energy of structure.
double physicalForce (double force) const
Undo normalization for a given force.
void convertToNormalizedUnits (Structure &structure) const
Convert one structure to normalized units.
void convertToPhysicalUnits (Structure &structure) const
Convert one structure to physical units.
std::size_t getNumExtrapolationWarnings () const
Count total number of extrapolation warnings encountered for all elements and symmetry functions.
void resetExtrapolationWarnings ()
Erase all extrapolation warnings and reset counters.
double getMeanEnergy () const
Getter for Mode::meanEnergy.
double getConvEnergy () const
Getter for Mode::convEnergy.
double getConvLength () const
Getter for Mode::convLength.
double getMaxCutoffRadius () const
Getter for Mode::maxCutoffRadius.
std::size_t getNumElements () const
Getter for Mode::numElements.
std::vector< std::size_t > getNumSymmetryFunctions () const
Get number of symmetry functions per element.
bool useNormalization () const
Check if normalization is enabled.
bool settingsKeywordExists (std::string const &keyword) const
Check if keyword was found in settings file.
std::string settingsGetValue (std::string const &keyword) const
Get value for given keyword in Settings instance.
std::vector< std::size_t > pruneSymmetryFunctionsRange (double threshold)
Prune symmetry functions according to their range and write settings file.
std::vector< std::size_t > pruneSymmetryFunctionsSensitivity (double threshold, std::vector< std::vector< double > > sensitivity)
Prune symmetry functions with sensitivity analysis data.
void writePrunedSettingsFile (std::vector< std::size_t > prune, std::string fileName="output.nn") const
Copy settings file but comment out lines provided.
void writeSettingsFile (std::ofstream *const &file) const
Write complete settings file.
Public Attributes
std::string fileNameSettings
std::string fileNameScaling
std::string formatWeightsFiles
Structure structure
Public Attributes inherited from nnp::Mode
ElementMap elementMap
Global element map, populated by setupElementMap().
Log log
Global log file.
Additional Inherited Members
Protected Attributes inherited from nnp::Mode
bool normalize
bool checkExtrapolationWarnings
std::size_t numElements
std::vector< std::size_t > minNeighbors
std::vector< double > minCutoffRadius
double maxCutoffRadius
double cutoffAlpha
double meanEnergy
double convEnergy
double convLength
Settings settings
SymmetryFunction::ScalingType scalingType
CutoffFunction::CutoffType cutoffType
std::vector< Element > elements
Detailed Description
Definition at line 27 of file Prediction.h.
Constructor & Destructor Documentation
Prediction::Prediction ()
Definition at line 26 of file Prediction.cpp.
                        : Mode(),
                            fileNameSettings  ("input.nn"          ),
                            fileNameScaling   ("scaling.data"      ),
                            formatWeightsFiles("weights.%03zu.data")
 {
 }
Member Function Documentation
void Prediction::readStructureFromFile (std::string const & fileName = "input.data")
Definition at line 43 of file Prediction.cpp.
References nnp::Mode::convEnergy, nnp::Mode::convLength, nnp::Mode::elementMap, nnp::Mode::meanEnergy, nnp::Mode::normalize, nnp::Structure::readFromFile(), nnp::Mode::removeEnergyOffset(), nnp::Structure::reset(), nnp::Structure::setElementMap(), structure, and nnp::Structure::toNormalizedUnits().
Referenced by main().
 {
     ifstream file;
     file.open(fileName.c_str());
     structure.reset();
     structure.setElementMap(elementMap);
     structure.readFromFile(fileName);
     removeEnergyOffset(structure);
     if (normalize)
     {
         structure.toNormalizedUnits(meanEnergy, convEnergy, convLength);
     }
     file.close();
     return;
 }
void Prediction::setup ()
Definition at line 33 of file Prediction.cpp.
References fileNameScaling, fileNameSettings, formatWeightsFiles, nnp::Mode::initialize(), nnp::Mode::loadSettingsFile(), nnp::Mode::setupGeneric(), nnp::Mode::setupNeuralNetworkWeights(), nnp::Mode::setupSymmetryFunctionScaling(), and nnp::Mode::setupSymmetryFunctionStatistics().
Referenced by main().
 {
     initialize();
     loadSettingsFile(fileNameSettings);
     setupGeneric();
     setupSymmetryFunctionScaling(fileNameScaling);
     setupNeuralNetworkWeights(formatWeightsFiles);
     setupSymmetryFunctionStatistics(false, false, true, false);
 }
void Prediction::predict ()
Definition at line 60 of file Prediction.cpp.
References nnp::Mode::addEnergyOffset(), nnp::Mode::calculateAtomicNeuralNetworks(), nnp::Mode::calculateEnergy(), nnp::Mode::calculateForces(), nnp::Structure::calculateNeighborList(), nnp::Mode::calculateSymmetryFunctionGroups(), nnp::Mode::calculateSymmetryFunctions(), nnp::Mode::convEnergy, nnp::Mode::convLength, nnp::Mode::maxCutoffRadius, nnp::Mode::meanEnergy, nnp::Mode::normalize, structure, and nnp::Structure::toPhysicalUnits().
Referenced by main().
 {
     structure.calculateNeighborList(maxCutoffRadius);
 #ifdef NOSFGROUPS
     calculateSymmetryFunctions(structure, true);
 #else
     calculateSymmetryFunctionGroups(structure, true);
 #endif
     calculateAtomicNeuralNetworks(structure, true);
     calculateEnergy(structure);
     calculateForces(structure);
     if (normalize)
     {
         structure.toPhysicalUnits(meanEnergy, convEnergy, convLength);
     }
     addEnergyOffset(structure, false);
     addEnergyOffset(structure, true);
     return;
 }
Member Data Documentation
std::string nnp::Prediction::fileNameSettings
Definition at line 35 of file Prediction.h.
Referenced by setup().
std::string nnp::Prediction::fileNameScaling
Definition at line 36 of file Prediction.h.
Referenced by setup().
std::string nnp::Prediction::formatWeightsFiles
Definition at line 37 of file Prediction.h.
Referenced by setup().
Structure nnp::Prediction::structure
Definition at line 38 of file Prediction.h.
Referenced by main(), predict(), and readStructureFromFile().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/Prediction.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/Prediction.cpp