n2p2 - A neural network potential package: /home/travis/build/CompPhysVienna/n2p2/src/application/nnp-cutoff/main.cpp File Reference
main.cpp File Reference
#include "CutoffFunction.h"
#include "Log.h"
#include "Stopwatch.h"
#include "utility.h"
#include <iostream>
#include <fstream>
Functions
void runTest (bool write)
void runTest (CutoffFunction::CutoffType cutoffType)
int main ()
Variables
CutoffFunction fc
Log log
ofstream logFile
Stopwatch swf
Stopwatch swdf
Stopwatch swfdf
size_t p = 100000000
double d = 0.99999 / p
double tbf = 0.0
double tbdf = 0.0
double tbfdf = 0.0
double tlf = 0.0
double tldf = 0.0
double tlfdf = 0.0
Function Documentation
void runTest (bool write)
Definition at line 42 of file main.cpp.
References p, nnp::Stopwatch::reset(), nnp::Stopwatch::start(), nnp::Stopwatch::stop(), nnp::strpr(), tldf, tlf, and tlfdf.
Referenced by main().
 {
     swf.reset();
     swf.start();
     for (size_t i = 0; i < p; ++i)
     {
         __asm__ __volatile__("");
     }
     tlf = swf.stop();
     if (write) log << strpr(" %10.2E %6.1f       ", tlf, tlf / tlf);
     swdf.reset();
     swdf.start();
     for (size_t i = 0; i < p; ++i)
     {
         __asm__ __volatile__("");
     }
     tldf = swdf.stop();
     if (write) log << strpr(" %10.2E %6.1f       ", tldf, tldf / tldf);
     swfdf.reset();
     swfdf.start();
     for (size_t i = 0; i < p; ++i)
     {
         __asm__ __volatile__("");
     }
     tlfdf = swfdf.stop();
     if (write) log << strpr(" %10.2E %6.1f        %10.2E %9.1f\n",
                             tlfdf,
                             tlfdf / tlfdf,
                             tlfdf - (tlf + tldf),
                             100.0 * tlfdf / (tlf + tldf));
 }
void runTest (CutoffFunction::CutoffType cutoffType)
Definition at line 76 of file main.cpp.
References d, nnp::CutoffFunction::df(), nnp::CutoffFunction::f(), nnp::CutoffFunction::fdf(), p, nnp::Stopwatch::reset(), nnp::CutoffFunction::setCutoffType(), nnp::Stopwatch::start(), nnp::Stopwatch::stop(), nnp::strpr(), tbdf, tbf, tbfdf, tldf, tlf, and tlfdf.
 {
     fc.setCutoffType(cutoffType);
     swf.reset();
     swf.start();
     for (size_t i = 0; i < p; ++i)
     {
         fc.f(i * d);
     }
     double tf = swf.stop();
     if (cutoffType == CutoffFunction::CT_HARD) tbf = tf;
     log << strpr(" %10.2E %6.1f %6.1f", tf, tf / tlf, tf / tbf);
     swdf.reset();
     swdf.start();
     for (size_t i = 0; i < p; ++i)
     {
         fc.df(i * d);
     }
     double tdf = swdf.stop();
     if (cutoffType == CutoffFunction::CT_HARD) tbdf = tdf;
     log << strpr(" %10.2E %6.1f %6.1f", tdf, tdf / tldf, tdf / tbdf);
     swfdf.reset();
     swfdf.start();
     for (size_t i = 0; i < p; ++i)
     {
         double f;
         double df;
         fc.fdf(i * d, f, df);
     }
     double tfdf = swfdf.stop();
     if (cutoffType == CutoffFunction::CT_HARD) tbfdf = tfdf;
     log << strpr(" %10.2E %6.1f %6.1f %10.2E %9.1f\n",
                  tfdf,
                  tfdf / tlfdf,
                  tfdf / tbfdf,
                  tfdf - (tf + tdf),
                  100.0 * tfdf / (tf + tdf));
 }
int main ()
Definition at line 119 of file main.cpp.
References logFile, nnp::Log::registerStreamPointer(), runTest(), nnp::CutoffFunction::setCutoffParameter(), and nnp::CutoffFunction::setCutoffRadius().
 {
     logFile.open("nnp-cutoff.log");
     log.registerStreamPointer(&logFile);
     log << "-------------------------------------------------------------------------------------------------------------\n";
     log << "Speed test tool for cutoff functions:\n";
     log << "-------------------------------------------------------------------------------------------------------------\n";
     log << "Column f     : Time for calling f   (no derivatives  ).\n";
     log << "Column df    : Time for calling df  (only derivatives).\n";
     log << "Column fdf   : Time for calling fdf (f and df at once).\n";
     log << "Column compL : Time compared to LOOP ONLY.\n";
     log << "Column compH : Time compared to CT_HARD.\n";
     log << "Column diff  : Time difference between calling f + df (separately) and fdf.\n";
     log << "Column ratio : Ratio time(fdf) / (time(f) + time(df)) in %.\n";
     log << "-------------------------------------------------------------------------------------------------------------\n";
     log << "CutoffType :       f [s]  compL  compH     df [s]  compL  compH     fdf[s]  compL  compH   diff [s] ratio [%]\n";
     log << "-------------------------------------------------------------------------------------------------------------\n";
     // Initialize...
     runTest(false);
     log << "LOOP ONLY  : ";
     runTest(true);
     fc.setCutoffRadius(1.0);
     log << "CT_HARD    : ";
     runTest(CutoffFunction::CT_HARD);
     log << "CT_COS     : ";
     fc.setCutoffParameter(0.0);
     runTest(CutoffFunction::CT_COS);
     log << "CT_TANHU   : ";
     runTest(CutoffFunction::CT_TANHU);
     log << "CT_TANH    : ";
     runTest(CutoffFunction::CT_TANH);
     log << "CT_EXP     : ";
     fc.setCutoffParameter(0.0);
     runTest(CutoffFunction::CT_EXP);
     log << "CT_POLY1   : ";
     fc.setCutoffParameter(0.0);
     runTest(CutoffFunction::CT_POLY1);
     log << "CT_POLY2   : ";
     fc.setCutoffParameter(0.0);
     runTest(CutoffFunction::CT_POLY2);
     log << "CT_POLY3   : ";
     fc.setCutoffParameter(0.0);
     runTest(CutoffFunction::CT_POLY3);
     log << "CT_POLY4   : ";
     fc.setCutoffParameter(0.0);
     runTest(CutoffFunction::CT_POLY4);
     logFile.close();
     return 0;
 }
Variable Documentation
CutoffFunction fc
Definition at line 27 of file main.cpp.
Referenced by nnp::SymmetryFunction::setCutoffFunction().
Log log
Definition at line 28 of file main.cpp.
Referenced by nnp::Settings::info(), main(), nnp::Settings::parseLines(), nnp::NeuralNetwork::propagateLayer(), nnp::Settings::readFile(), nnp::Settings::sanityCheck(), and nnp::SetupAnalysis::writeSymmetryFunctionShape().
ofstream logFile
Definition at line 29 of file main.cpp.
Referenced by main().
Stopwatch swf
Definition at line 30 of file main.cpp.
Stopwatch swdf
Definition at line 31 of file main.cpp.
Stopwatch swfdf
Definition at line 32 of file main.cpp.
size_t p = 100000000
Definition at line 33 of file main.cpp.
Referenced by nnp::SymmetryFunctionWeightedAngular::calculateRadialPart(), nnp::SymmetryFunctionAngularWide::calculateRadialPart(), nnp::SymmetryFunctionAngularNarrow::calculateRadialPart(), nnp::InterfaceLammps::extractEWBuffer(), nnp::InterfaceLammps::fillEWBuffer(), nnp::Dataset::recvStructure(), runTest(), nnp::Dataset::sendStructure(), and nnp::Training::update().
double d = 0.99999 / p
Definition at line 34 of file main.cpp.
Referenced by nnp::InterfaceLammps::extractEWBuffer(), nnp::SymmetryFunctionStatistics::getExtrapolationWarningLines(), and runTest().
double tbf = 0.0
Definition at line 35 of file main.cpp.
Referenced by runTest().
double tbdf = 0.0
Definition at line 36 of file main.cpp.
Referenced by runTest().
double tbfdf = 0.0
Definition at line 37 of file main.cpp.
Referenced by runTest().
double tlf = 0.0
Definition at line 38 of file main.cpp.
Referenced by runTest().
double tldf = 0.0
Definition at line 39 of file main.cpp.
Referenced by runTest().
double tlfdf = 0.0
Definition at line 40 of file main.cpp.
Referenced by runTest().